### ISSUE TITLE
Does your method incorporate features into each node? 

### ISSUE THREAD

**Issue by zmce2018** [Jimmy-7664/STD-MAE#10]
You are dealing with spatio temporal issues so I wonder if your model supports adding features into each node?

**Comment by Jimmy-7664** [comment]
Hi, could you explain more about your idea? What do you mean of "adding features into each node"? Do you mean that the channel dimension can be set to more than 1?

**Comment by Jimmy-7664** [comment]
I got your idea. I believe that this is absolutely a feasible operation.

**Comment by Jimmy-7664** [comment]
Moreover, you may need to modify some parts of code to meet your new features. I hope everything goes smoothly for you. If there are any further questions, we can continue to discuss them.
