### ISSUE TITLE
Question about Downstream

### ISSUE THREAD

**Issue by sugar-hub** [Jimmy-7664/STD-MAE#12]
Hi, there!

First, I would like to appreciate you for your opening source code. I'm very interested to the _Downstream Spatiotemporal Predictor_  in your essay. However, I haven't found any code about it. Could you show me where is it?
![Uploading Screenshot 2024-05-30 at 19.18.05.png…]()

**Comment by Jimmy-7664** [comment]
Hi, thank you for appreciating our work.
As we test many downstream spatiotemporal predictors and we choose Graph Wavenet as our backend model, so we currently provide it [here](https://github.com/Jimmy-7664/STD-MAE/tree/main/stdmae/stdmae_arch/graphwavenet). For other models like DCRNN, STID, and STAEformer, you can either find them in their official implementation github repo or you can find them in these two libraries: [BasicTS](https://github.com/zezhishao/BasicTS) and [Torch-MTS](https://github.com/XDZhelheim/Torch-MTS).
