### ISSUE TITLE
Question about Pretraining 

### ISSUE THREAD

**Issue by wgc-research** [Jimmy-7664/STD-MAE#13]
Thank you for such good work, I like it!
However, when I reproduced the codes, I found the pretraining process is too long (5 minutes for 1 epoch), that means you need one day for the pretraining, is that right?
I reproduced the pretraining process based on GPU 3090.

**Comment by Jimmy-7664** [comment]
Yeah, you are right. Pre-training is a time consuming operation because it introduces long input. Which dataset are you working with? 5 mins per epoch is a normal occurrence. You may consider to use multi-GPUs to accelerate the pre-training phase.

**Comment by wgc-research** [comment]
Thank you. I worked on the PEMS04 dataset, and I just want to check it.
