### ISSUE TITLE
预训练时是否使用了额外数据集

### ISSUE THREAD

**Issue by wayhoww** [Jimmy-7664/STD-MAE#15]
我在 https://paperswithcode.com/sota/traffic-prediction-on-pems04 中, 看到 STD-MAE 的 “Extra Training Data” 列被打上了勾. 但我看代码里面, STD-MAE 并没有使用额外训练数据, 每个数据集上的预训练都只用了该数据集中的数据.

**Comment by Jimmy-7664** [comment]
是的这里打了勾，我的理解是相对于非预训练的模型（12 steps=>12 steps），STD-MAE使用了更长的输入数据做预训练（虽然是相同的数据集），可以看作是一种额外的训练数据。

**Comment by wayhoww** [comment]
感谢作者回复, 清楚了.
