### ISSUE TITLE
推理问题

### ISSUE THREAD

**Issue by kakaroy123** [Jimmy-7664/STD-MAE#17]
训练好的模型怎么用来推理呢，怎么得到每一次的预测结果？

**Comment by Jimmy-7664** [comment]
将训练好的权重加载到模型中进行forward就可以了

**Comment by kakaroy123** [comment]
> 将训练好的权重加载到模型中进行forward就可以了

这部分有例子么？训练好的权重是指SMAE和TMAE训练出来的那两个结果么？

**Comment by Jimmy-7664** [comment]
“训练好的权重是指SMAE和TMAE训练出来的那两个结果么？”

不是的，是训练结束后的STD-MAE.
SMAE和TMAE是预训练表征学习的结果，STD-MAE是预训练+预测的模型。具体可以参考文章中的内容。

**Comment by kakaroy123** [comment]
> “训练好的权重是指SMAE和TMAE训练出来的那两个结果么？”
> 
> 不是的，是训练结束后的STD-MAE. SMAE和TMAE是预训练表征学习的结果，STD-MAE是预训练+预测的模型。具体可以参考文章中的内容。

哦哦 了解了 感谢！ 就是拿STD-MAE训练结果来做推理，推理部分的代码有示例么？

**Comment by Jimmy-7664** [comment]
```
import torch
from stdmae import STDMAE
# load packages
import os
import sys
PROJECT_DIR = os.path.abspath(os.path.abspath(''))
print(PROJECT_DIR)
sys.path.append(PROJECT_DIR)

import numpy as np
import torch as th
import matplotlib.pyplot as plt
from basicts.utils.serialization import load_adj

from basicts.utils import load_pkl
from basicts.data import SCALER_REGISTRY
import numpy as np
import torch as th
import matplotlib.pyplot as plt
pre_trained_tmae_path="../mask_save/TMAE_PEMS-BAY.pt"
pre_trained_smae_path="../mask_save/SMAE_PEMS-BAY.pt"
stmdmae_path="../mask_save/STDMAE_PEMS-BAY.pt"
device = torch.device("cpu")
adj_mx, _ = load_adj("../datasets/PEMS-BAY/adj_mx.pkl", "doubletransition")

stdmae=STDMAE(
    dataset_name="PEMS-BAY",
    pre_trained_tmae_path= pre_trained_tmae_path,
    pre_trained_smae_path= pre_trained_smae_path,
    mask_args={
                    "patch_size":12,
                    "in_channel":1,
                    "embed_dim":96,
                    "num_heads":4,
                    "mlp_ratio":4,
                    "dropout":0.1,
                    "mask_ratio":0.25,
                    "encoder_depth":4,
                    "decoder_depth":1,
                    "num_token":864,
                    "mode":"forecasting"
    },
    backend_args={
                    "num_nodes" : 325,
                    "supports"  :[torch.tensor(i) for i in adj_mx],
                    "dropout"   : 0.3,
                    "gcn_bool"  : True,
                    "addaptadj" : True,
                    "aptinit"   : None,
                    "in_dim"    : 2,
                    "out_dim"   : 12,
                    "residual_channels" : 32,
                    "dilation_channels" : 32,
                    "skip_channels"     : 256,
                    "end_channels"      : 512,
                    "kernel_size"       : 2,
                    "blocks"            : 4,
                    "layers"            : 2
    }
)

checkpoint_dict = torch.load(stmdmae_path,map_location=torch.device('cpu'))
stdmae.load_state_dict(checkpoint_dict["model_state_dict"])

# # freeze parameters
for param in stdmae.parameters():
    param.requires_grad = False

```
For your reference.

**Comment by kakaroy123** [comment]
> ```
> import torch
> from stdmae import STDMAE
> # load packages
> import os
> import sys
> PROJECT_DIR = os.path.abspath(os.path.abspath(''))
> print(PROJECT_DIR)
> sys.path.append(PROJECT_DIR)
> 
> import numpy as np
> import torch as th
> import matplotlib.pyplot as plt
> from basicts.utils.serialization import load_adj
> 
> from basicts.utils import load_pkl
> from basicts.data import SCALER_REGISTRY
> import numpy as np
> import torch as th
> import matplotlib.pyplot as plt
> pre_trained_tmae_path="../mask_save/TMAE_PEMS-BAY.pt"
> pre_trained_smae_path="../mask_save/SMAE_PEMS-BAY.pt"
> stmdmae_path="../mask_save/STDMAE_PEMS-BAY.pt"
> device = torch.device("cpu")
> adj_mx, _ = load_adj("../datasets/PEMS-BAY/adj_mx.pkl", "doubletransition")
> 
> stdmae=STDMAE(
>     dataset_name="PEMS-BAY",
>     pre_trained_tmae_path= pre_trained_tmae_path,
>     pre_trained_smae_path= pre_trained_smae_path,
>     mask_args={
>                     "patch_size":12,
>                     "in_channel":1,
>                     "embed_dim":96,
>                     "num_heads":4,
>                     "mlp_ratio":4,
>                     "dropout":0.1,
>                     "mask_ratio":0.25,
>                     "encoder_depth":4,
>                     "decoder_depth":1,
>                     "num_token":864,
>                     "mode":"forecasting"
>     },
>     backend_args={
>                     "num_nodes" : 325,
>                     "supports"  :[torch.tensor(i) for i in adj_mx],
>                     "dropout"   : 0.3,
>                     "gcn_bool"  : True,
>                     "addaptadj" : True,
>                     "aptinit"   : None,
>                     "in_dim"    : 2,
>                     "out_dim"   : 12,
>                     "residual_channels" : 32,
>                     "dilation_channels" : 32,
>                     "skip_channels"     : 256,
>                     "end_channels"      : 512,
>                     "kernel_size"       : 2,
>                     "blocks"            : 4,
>                     "layers"            : 2
>     }
> )
> 
> checkpoint_dict = torch.load(stmdmae_path,map_location=torch.device('cpu'))
> stdmae.load_state_dict(checkpoint_dict["model_state_dict"])
> 
> # # freeze parameters
> for param in stdmae.parameters():
>     param.requires_grad = False
> ```
> 
> For your reference.

Thx !

**Comment by Sjjnb666** [comment]
请问如何读取数据集进行推理

**Comment by Jimmy-7664** [comment]
@Sjjnb666 读取下载后想要使用的数据集进行推理即可。
以PEMS04数据集为例:
```
import numpy as np
pems04 = np.load('./PEMS04.npz')['data']

```

以PEMS-BAY数据集为例:

```
import pandas as pd
df = pd.HDFStore('./PEMS-BAY.h5')['/speed']

```
