### ISSUE TITLE
我如何才能找到scaler_in2016_out12.pkl这个文件呢？

### ISSUE THREAD

**Issue by beibei12345** [Jimmy-7664/STD-MAE#18]
一运行就报错，找不到文件：
`(python3.9_for_STDMAE) PS F:\PycharmProjects\pythonProject\交通流论文复现\STD-MAE-main> python stdmae/run.py --cfg='stdmae/TMAE_PEMS08.py' --gpus='0'
2024-08-30 02:32:08,973 - easytorch-launcher - INFO - Launching EasyTorch training.
DESCRIPTION: TMAE(PEMS08) configuration
RUNNER: <class 'stdmae.stdmae_runner.mask_runner.MaskRunner'>
DATASET_CLS: <class 'basicts.data.dataset.TimeSeriesForecastingDataset'>
DATASET_NAME: PEMS08
DATASET_TYPE: Traffic flow
DATASET_INPUT_LEN: 2016
DATASET_OUTPUT_LEN: 12
GPU_NUM: 1
ENV:
  SEED: 659003
  CUDNN:
    ENABLED: True
MODEL:
  NAME: TMAE
  ARCH: <class 'stdmae.stdmae_arch.mask.mask.Mask'>
  PARAM:
    patch_size: 12
    in_channel: 1
    embed_dim: 96
    num_heads: 4
    mlp_ratio: 4
    dropout: 0.1
    mask_ratio: 0.25
    encoder_depth: 4
    decoder_depth: 1
    spatial: False
    mode: pre-train
  FORWARD_FEATURES: [0]
  TARGET_FEATURES: [0]
TRAIN:
  LOSS: masked_mae
  OPTIM:
    TYPE: Adam
    PARAM:
      lr: 0.001
      weight_decay: 0
      eps: 1e-08
      betas: [0.9, 0.95]
  LR_SCHEDULER:
    TYPE: MultiStepLR
    PARAM:
      milestones: [50]
      gamma: 0.5
  CLIP_GRAD_PARAM:
    max_norm: 5.0
  NUM_EPOCHS: 200
  CKPT_SAVE_DIR: checkpoints\TMAE_200
  DATA:
    DIR: datasets/PEMS08
    BATCH_SIZE: 4
    PREFETCH: False
    SHUFFLE: True
    NUM_WORKERS: 2
    PIN_MEMORY: True
  NULL_VAL: 0.0
VAL:
  INTERVAL: 1
  DATA:
    DIR: datasets/PEMS08
    BATCH_SIZE: 4
    PREFETCH: False
    SHUFFLE: False
    NUM_WORKERS: 2
    PIN_MEMORY: True
TEST:
  INTERVAL: 1
  DATA:
    DIR: datasets/PEMS08
    BATCH_SIZE: 4
    PREFETCH: False
    SHUFFLE: False
    NUM_WORKERS: 2
    PIN_MEMORY: True

2024-08-30 02:32:09,726 - easytorch-env - INFO - Use GPUs 0.
2024-08-30 02:32:09,775 - easytorch-launcher - INFO - Initializing runner "<class 'stdmae.stdmae_runner.mask_runner.MaskRunner'>"
2024-08-30 02:32:09,775 - easytorch-env - INFO - Disable TF32 mode
2024-08-30 02:32:09,779 - easytorch - INFO - Set ckpt save dir: 'checkpoints\TMAE_200\dc50e1ee61f8463c81a038b8d23c9889'
2024-08-30 02:32:09,779 - easytorch - INFO - Building model.
Unable to load data  datasets/PEMS08/scaler_in2016_out12.pkl : [Errno 2] No such file or directory: 'datasets/PEMS08/scaler_in2016_out12.pkl'
Traceback (most recent call last):
  File "F:\PycharmProjects\pythonProject\交通流论文复现\STD-MAE-main\basicts\launcher.py", line 20, in launch_training
    easytorch.launch_training(cfg=cfg, devices=gpus, node_rank=node_rank)
TypeError: launch_training() got an unexpected keyword argument 'devices'
    self.scaler = load_pkl("datasets/" + self.dataset_name + "/scaler_in{0}_out{1}.pkl".format(
  File "F:\PycharmProjects\pythonProject\交通流论文复现\STD-MAE-main\basicts\utils\serialization.py", line 20, in load_pkl
    with open(pickle_file, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/PEMS08/scaler_in2016_out12.pkl'`

**Comment by Jimmy-7664** [comment]
@beibei12345 数据处理部分在README.md中有提到，可以使用以下命令来获得相关的数据。
`` bash scripts/data_preparation/all.sh ``

**Comment by Ryan88kim** [comment]
TypeError: launch_training() got an unexpected keyword argument 'devices'

how to fix?
