### ISSUE TITLE
Inquiries about the training log of TMAE and SMAE.

### ISSUE THREAD

**Issue by zezhishao** [Jimmy-7664/STD-MAE#19]
Dear authors,

Thank you for your excellent work! I am integrating STD-MAE into [BasicTS](https://github.com/GestaltCogTeam/BasicTS). Do you still have the training logs for TMAE and SMAE? I would like to use them to verify if my reproduction is accurate.

Thank you!

**Comment by Jimmy-7664** [comment]
Dear zezhi, 
Thank you for your message! We really appreciate your interest in integrating STD-MAE into BasicTS. I will upload the training logs for TMAE and SMAE within this week for you to verify the reproduction. Also, I often read and admire your many outstanding works in this domain.  : )

**Comment by zezhishao** [comment]
You're too kind! STD-MAE is an excellent work, and I'm looking forward to more exciting research from you in the future.

**Comment by Jimmy-7664** [comment]
I have uploaded the logs of TMAE and SMAE [here](https://github.com/Jimmy-7664/STD-MAE/tree/main/checkpoints) for your reference. If there’s anything else I can assist you with, please don’t hesitate to reach out. : )

**Comment by zezhishao** [comment]
Thanks very much for your quick response!

**Comment by zezhishao** [comment]
Thanks for your help, STD-MAE has now been added to BasicTS with correct (and even sightly better) performance~

**Comment by Jimmy-7664** [comment]
Great news! Thanks a lot for your help! I will also update this information in the README.md. Looking forward to further collaboration!
