### ISSUE TITLE
launch_training

### ISSUE THREAD

**Issue by zzzdaq** [Jimmy-7664/STD-MAE#2]
May I ask if the definition of launch_training is missing in the code? I am looking forward to receiving your reply.

**Comment by Jimmy-7664** [comment]
Sry, I don't get your point. Could you provide more information about the error?

**Comment by zzzdaq** [comment]
"mudule easytorch has no attribute launch_training" occurred when I was replicating the code, but I upgraded or lowered the version of torch to no effect, I guessed that something was wrong with "launch_training".

**Comment by QHofmann** [comment]
> “mudule easytorch has no attribute launch_training”发生在我复制代码时，但我升级或降低了 torch 的版本没有效果，我猜“launch_training”有问题。

There is no import lunch_training for the easytorch package, github and pypi both have the easytorch package, but there are still a lot of mistakes that happen in easytorch

**Comment by NonCover** [comment]
I meet same problem。

**Comment by Jimmy-7664** [comment]
Dear all, sorry for the late respone. I just test STD-MAE on a totally new Linux Server. It works well.
It seems that your error is related to the package version. Please make sure that you use the same version as the `requirements.txt`. Moreover, I recommend to create a new conda environment to test this repo.

**Comment by 15623152911** [comment]
> I meet same problem。

Have you solved this problem? How was it specifically resolved? Thank you

**Comment by Jimmy-7664** [comment]
Hi, could you provide more information about the version of torch and easytorch？ @15623152911

**Comment by QHofmann** [comment]
我用的这个版本




Moonlight.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Jimmy-7664/STD_MAE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月28日(星期四) 晚上7:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Jimmy-7664/STD_MAE] launch_training (Issue #2)





 
Hi, could you provide more information about the version of torch and easytorch？ @15623152911

**Comment by QHofmann** [comment]
我用的这个版本，改了点东西，反正可以用




Moonlight.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Jimmy-7664/STD_MAE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月28日(星期四) 晚上7:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Jimmy-7664/STD_MAE] launch_training (Issue #2)





  
I meet same problem。
  
Have you solved this problem? How was it specifically resolved? Thank you

**Comment by QHofmann** [comment]
[
[easytorch.zip](https://github.com/Jimmy-7664/STD_MAE/files/14824846/easytorch.zip)
](url)


这是我在网上自己下的，又改了改，但可以用

**Comment by Jimmy-7664** [comment]
> [ [easytorch.zip](https://github.com/Jimmy-7664/STD_MAE/files/14824846/easytorch.zip) ](url)
> 
> 这是我在网上自己下的，又改了改，但可以用

I recommend you to use `anaconda` to control your python environments.

**Comment by Jimmy-7664** [comment]
> > Hi, could you provide more information about the version of torch and easytorch？：） @15623152911
> > ![QQ图片20240401223630](https://private-user-images.githubusercontent.com/165275556/318465214-4e49a02b-79cc-4f7a-a6dc-fcd61677b308.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5ODQ5ODcsIm5iZiI6MTcxMTk4NDY4NywicGF0aCI6Ii8xNjUyNzU1NTYvMzE4NDY1MjE0LTRlNDlhMDJiLTc5Y2MtNGY3YS1hNmRjLWZjZDYxNjc3YjMwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQxNTE4MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzU5NzkyNDJjYTkxNzc1YWQ0ODRkNjc4MjlhYjA1YTgwODVkMDEzYmU4ZGIxZDFkY2NkNzRmNzhlNWZiNzk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bdNxBz7RAuDUmtIusKxXfbZaLd7un35ec1XCpnywWg8)
> 
> > ![QQ图片20240401223653](https://private-user-images.githubusercontent.com/165275556/318465234-a6ad8d28-b397-477c-a98d-a84512fc6e03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5ODQ5ODcsIm5iZiI6MTcxMTk4NDY4NywicGF0aCI6Ii8xNjUyNzU1NTYvMzE4NDY1MjM0LWE2YWQ4ZDI4LWIzOTctNDc3Yy1hOThkLWE4NDUxMmZjNmUwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQxNTE4MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YWJkYWQ4MWJiYTM5ZjQ3MDE3Y2IwNmM4ZDliNDY3MGM4ZmRiYzhlZTI2YzBlNjI4N2I3ZDQyNDcwYzhkZDE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jzixRlTH6992R11j-meFwu260laNLk4o4mFuwCsYQ2I)

It seems the versions are right. Could you provide how you run the code and more detailed error information?

Here is how I test this repo on Linux server. I suggest that you already download the data.

`conda create -n test python=3.9`
`git clone https://github.com/Jimmy-7664/STD_MAE.git`
`conda activate test`
`cd STD_MAE`
`pip install -r requirements.txt`
`screen -d -m python stdmae/run.py --cfg='stdmae/TMAE_PEMS03.py' --gpus='0' `
@15623152911

**Comment by 15623152911** [comment]
> > > Hi, could you provide more information about the version of torch and easytorch？：） @15623152911
> > > ![QQ图片20240401223630](https://private-user-images.githubusercontent.com/165275556/318465214-4e49a02b-79cc-4f7a-a6dc-fcd61677b308.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5ODQ5ODcsIm5iZiI6MTcxMTk4NDY4NywicGF0aCI6Ii8xNjUyNzU1NTYvMzE4NDY1MjE0LTRlNDlhMDJiLTc5Y2MtNGY3YS1hNmRjLWZjZDYxNjc3YjMwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQxNTE4MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzU5NzkyNDJjYTkxNzc1YWQ0ODRkNjc4MjlhYjA1YTgwODVkMDEzYmU4ZGIxZDFkY2NkNzRmNzhlNWZiNzk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bdNxBz7RAuDUmtIusKxXfbZaLd7un35ec1XCpnywWg8)
> > 
> > 
> > > ![QQ图片20240401223653](https://private-user-images.githubusercontent.com/165275556/318465234-a6ad8d28-b397-477c-a98d-a84512fc6e03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5ODQ5ODcsIm5iZiI6MTcxMTk4NDY4NywicGF0aCI6Ii8xNjUyNzU1NTYvMzE4NDY1MjM0LWE2YWQ4ZDI4LWIzOTctNDc3Yy1hOThkLWE4NDUxMmZjNmUwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQxNTE4MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YWJkYWQ4MWJiYTM5ZjQ3MDE3Y2IwNmM4ZDliNDY3MGM4ZmRiYzhlZTI2YzBlNjI4N2I3ZDQyNDcwYzhkZDE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jzixRlTH6992R11j-meFwu260laNLk4o4mFuwCsYQ2I)
> 
> It seems the versions are right. Could you provide how you run the code and more detailed error information?
> 
> Here is how I test this repo on Linux server. I suggest that you already prepared the data.
> 
> `conda create -n test python=3.9` `git clone https://github.com/Jimmy-7664/STD_MAE.git` `conda activate test` `cd STD_MAE` `pip install -r requirements.txt` `screen -d -m python stdmae/run.py --cfg='stdmae/TMAE_PEMS03.py' --gpus='0' ` @15623152911
![IMG_20240402_213424](https://github.com/Jimmy-7664/STD_MAE/assets/165275556/d7e5d0d6-b346-4f14-8e80-8e87dd180123)
run.py runs incorrectly

**Comment by Jimmy-7664** [comment]
@15623152911 @NonCover @QHofmann @zzzdaq 

Dear all, sorry for the bother. I find the reason behind this issue. I placed an error package in requirements.txt. Please use `pip uninstall easytorch` to uninstall the package `easytorch`. The right package name is `easy_torch`. I already fix the `requirements.txt`file now. Or you can create a new conda environment to install the package through the new `requirements.txt` file.

**Comment by Jimmy-7664** [comment]
If you find that the issue has been resolved or you are still receiving the error message, please comment on this issue and I will address it further.

**Comment by Jimmy-7664** [comment]
Moreover, please make sure run the code under `STD_MAE` directory with command in the `README.md`. 

**Do not enter the directory `STD_MAE/stdmae` and run the command `python run.py`**
