### ISSUE TITLE
Metr-la And Pems-Bay

### ISSUE THREAD

**Issue by zwy262325** [Jimmy-7664/STD-MAE#21]
请问有预训练部分Metr-la和Pems-Bay的py文件吗？

**Comment by Jimmy-7664** [comment]
有的，我找一下，会在两天内上传 : )

**Comment by zwy262325** [comment]
收到！！能否把pt文件也传一下，麻烦您啦~~~///(^v^)\\\~~~

**Comment by Jimmy-7664** [comment]
pt文件在之前的服务器里，由于我更换了单位暂时没有权限访问了。不过我已经更新了LA和BAY的相关文件(包括数据处理和配置文件) ，下载数据集后运行即可

**Comment by zwy262325** [comment]
好的，谢谢您^_^



发自我的iPhone


------------------ Original ------------------
From: Haotian Gao ***@***.***&gt;
Date: Thu, Dec 5, 2024 11:46 PM
To: Jimmy-7664/STD-MAE ***@***.***&gt;
Cc: zwy262325 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Jimmy-7664/STD-MAE] Metr-la And Pems-Bay (Issue #21)
