### ISSUE TITLE
May I ask why the upper and lower displays are different?

### ISSUE THREAD

**Issue by user142isme** [Jimmy-7664/STD-MAE#4]
![111](https://github.com/Jimmy-7664/STD_MAE/assets/92203104/7254b0ef-bf4d-4d96-871a-99a6b893e99e)

Only when the project is running, it shows that there are 0 GPUs, and when testing, there is one GPU.

**Comment by Jimmy-7664** [comment]
Could you provide more information about the OS version and run a python file with following commands?
```
import torch 
print(torch.cuda.is_available()) 
print(torch.cuda.device_count()) 
print(torch.version.cuda) 
```

**Comment by user142isme** [comment]
![333](https://github.com/Jimmy-7664/STD_MAE/assets/92203104/a8375c71-bc52-4b63-8658-3bf6b6e5d195)

Thank you for your reply. I have provided the content you need, and I have checked the requirements that need to be downloaded for this environment and they are consistent with your requirements.txt.

**Comment by Jimmy-7664** [comment]
```
import torch 
print(torch.cuda.is_available()) 
print(torch.cuda.device_count()) 
print(torch.version.cuda) 
```
Could you put the above code into a file such as`test.py` and use the command for example `python test.py` to run it?

**Comment by Jimmy-7664** [comment]
Happy to hear your question solved. The problem is about the version of package `easy-torch`. I will modify the launcher file to better fit the version of different `easy-torch`.

**Comment by Jimmy-7664** [comment]
By the way, the original code of `STD-MAE` uses `easytorch.launch_training(cfg=cfg, gpus=gpus, node_rank=node_rank)`.
The code `easytorch.launch_training(cfg=cfg, devices=gpus, node_rank=node_rank)` is for new version of `easy-torch`.
 If you have furthur question, you can ask here.

**Comment by Jimmy-7664** [comment]
Dear @user142isme, when you get the error about  `0 GPU count`, how do you run the code? Do you use command `python stdmae/run.py ` or command `python stdmae/run.py --cfg='stdmae/TMAE_PEMS03.py' --gpus='0' `?

**Comment by user142isme** [comment]
![000](https://github.com/Jimmy-7664/STD_MAE/assets/92203104/9530757b-24f3-46b0-940b-ef481b496beb)

Thank you for your very patient reply. Because I am using a windows system, I use python stdmae/run.py --cfg stdmae/TMAE_PEMS03.py --gpus '0' to run the program.

**Comment by Jimmy-7664** [comment]
The problem seems to be related to the environment. You can try it on Linux Server and once you find that the problem is solved or still happens please comment on this issue. I will try to figure it out.
