### ISSUE TITLE
如何引用这篇文章呢

### ISSUE THREAD

**Issue by OvOYu** [Jimmy-7664/STD-MAE#6]
你能提供吗老哥 除了arxiv的

**Comment by Jimmy-7664** [comment]
感谢对于我们工作的认可，STD-MAE已被IJCAI24接收，我们将很快（最近几天）更新最新版的arXiv。其中包括新的文章标题（目前arXiv的标题为Spatio-Temporal-Decoupled Masked Pre-training: Benchmarked on Traffic Forecasting）以及一些新的实验结果。目前你可以使用
```
@article{gao2023spatio,
  title={Spatio-Temporal-Decoupled Masked Pre-training for Traffic Forecasting},
  author={Gao, Haotian and Jiang, Renhe and Dong, Zheng and Deng, Jinliang and Song, Xuan},
  journal={arXiv preprint arXiv:2312.00516},
  year={2023}
}
```
来引用STD-MAE的arXiv版本。

**Comment by Jimmy-7664** [comment]
@OvOYu 我们刚刚更新了新的[README.md](https://github.com/Jimmy-7664/STD-MAE/blob/main/README.md),我想你可以获得更多需要的信息。再次感谢你的支持 ：）
